import{acBtu,dehumidifier,cfmByAch,ach,bathFan,garageVent,btuToTons,tonsToBtu,btuToKw,kwToBtu,pintsToLiters,litersToPints,fmt,BOUNDARY}from'./calculators.mjs';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)],num=(f,k,d=0)=>Number(f.elements[k]?.value||d),val=(f,k,d='')=>String(f.elements[k]?.value||d),chk=(f,k)=>Boolean(f.elements[k]?.checked),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function input(f){return{lengthFt:num(f,'lengthFt',12),widthFt:num(f,'widthFt',10),areaSqft:num(f,'areaSqft',0),ceilingHeightFt:num(f,'ceilingHeightFt',8),heightFt:num(f,'heightFt',8),sunExposure:val(f,'sunExposure','average'),occupants:num(f,'occupants',2),kitchen:chk(f,'kitchen'),insulation:val(f,'insulation','average'),dampness:val(f,'dampness','damp'),basement:chk(f,'basement'),temperatureF:num(f,'temperatureF',70),waterIntrusion:chk(f,'waterIntrusion'),continuousDrain:chk(f,'continuousDrain'),targetAch:num(f,'targetAch',6),cfm:num(f,'cfm',100),toilet:num(f,'toilet',1),shower:num(f,'shower',1),tub:num(f,'tub',0),jettedTub:num(f,'jettedTub',0),ductLengthFt:num(f,'ductLengthFt',10),btu:num(f,'btu',12000),tons:num(f,'tons',1),kw:num(f,'kw',3.5),pints:num(f,'pints',50),liters:num(f,'liters',24)}}
const metric=(k,v,u='')=>`<div class=metric><strong>${v}${u?' '+u:''}</strong><span>${k}</span></div>`,warn=a=>a.map(x=>`<div class=warning>${esc(x)}</div>`).join('');
function render(f){const t=f.dataset.tool,x=input(f);let h='';if(['ac','window-ac','portable-ac'].includes(t)){const r=acBtu(x);h=`<div class=result-main>${t==='portable-ac'?'Portable AC range':t==='window-ac'?'Window AC range':'Room AC size'}: ${fmt(r.range.low)}-${fmt(r.range.high)} BTU/h</div><p>${fmt(r.tonsLow,1)}-${fmt(r.tonsHigh,1)} tons. Common sizes: ${r.commonSizes.map(v=>fmt(v)+' BTU').join(', ')}.</p><div class=metric-list>${metric('Area',fmt(r.areaSqft),'sq ft')}${metric('Volume',fmt(r.volumeCuft),'cu ft')}${metric('Base',fmt(r.baseBtu),'BTU/h')}${metric('Adjusted midpoint',fmt(r.adjustedBtu),'BTU/h')}</div><pre class=code>base_BTU = area × 20\nrange = adjusted_BTU × 90%-110%</pre><ul>${r.adjustments.map(a=>`<li>${esc(a[0])}: ${fmt(a[1])} BTU/h (${esc(a[2])})</li>`).join('')}</ul>${t==='portable-ac'?'<div class=warning>Check SACC, CEER, hose type, exhaust sealing, and product label.</div>':''}${warn(r.warnings)}`}
else if(['dehumidifier','basement-dehumidifier'].includes(t)){const r=dehumidifier({...x,basement:t==='basement-dehumidifier'||x.basement});h=`<div class=result-main>Estimated dehumidifier: ${fmt(r.range.low)}-${fmt(r.range.high)} pints/day</div><p>Class: ${esc(r.productClass)}. ${esc(r.drainageRecommendation)}</p><div class=metric-list>${metric('Area',fmt(r.areaSqft),'sq ft')}${metric('Low',fmt(r.range.low),'pints/day')}${metric('High',fmt(r.range.high),'pints/day')}${metric('High in liters',fmt(pintsToLiters(r.range.high),1),'L/day')}</div><pre class=code>base_pints_per_day = lookup(area, dampness)</pre>${warn(r.warnings)}`}
else if(t==='cfm-by-ach'){const r=cfmByAch(x);h=`<div class=result-main>Required airflow: ${fmt(r.cfm)} CFM</div><div class=metric-list>${metric('Volume',fmt(r.volumeCuft),'cu ft')}${metric('Target ACH',fmt(r.targetAch,1),'ACH')}${metric('CFM',fmt(r.cfm),'CFM')}</div><pre class=code>CFM = volume × ACH ÷ 60</pre>${warn(r.warnings)}`}
else if(t==='garage'){const r=garageVent(x);h=`<div class=result-main>Garage airflow: ${fmt(r.cfm)} CFM</div><pre class=code>CFM = garage_volume × target_ACH ÷ 60</pre>${warn(r.warnings)}`}
else if(t==='ach'){const r=ach(x);h=`<div class=result-main>Air changes: ${fmt(r.ach,1)} ACH</div><pre class=code>ACH = CFM × 60 ÷ volume</pre>${warn(r.warnings)}`}
else if(t==='bathroom-fan'){const r=bathFan(x);h=`<div class=result-main>Bathroom fan: ${fmt(r.recommendedCfm)} CFM</div><div class=metric-list>${metric('Area rule',fmt(r.areaRuleCfm),'CFM')}${metric('Fixture rule',fmt(r.fixtureRuleCfm),'CFM')}</div><pre class=code>CFM = max(area × 1, 50, fixture rule)</pre>${warn(r.warnings)}`}
else if(t==='tonnage'){h=`<div class=result-main>${fmt(x.btu)} BTU/h = ${fmt(btuToTons(x.btu),2)} tons</div><p>${fmt(x.tons,2)} tons = ${fmt(tonsToBtu(x.tons))} BTU/h.</p>${warn([BOUNDARY])}`}
else if(t==='btu-kw'){h=`<div class=result-main>${fmt(x.btu)} BTU/h = ${fmt(btuToKw(x.btu),2)} thermal kW</div><p>${fmt(x.kw,2)} thermal kW = ${fmt(kwToBtu(x.kw))} BTU/h. Thermal kW is not electrical input.</p>${warn([BOUNDARY])}`}
else if(t==='pints-liters'){h=`<div class=result-main>${fmt(x.pints)} pints = ${fmt(pintsToLiters(x.pints),1)} liters</div><p>${fmt(x.liters,1)} liters = ${fmt(litersToPints(x.liters),1)} pints.</p>${warn([BOUNDARY])}`}
$('[data-result]',f.closest('[data-tool-shell]')).innerHTML=h}
function hydrate(f){const p=new URLSearchParams(location.search);for(const[k,v]of p){const e=f.elements[k];if(!e)continue;if(e.type==='checkbox')e.checked=v==='on'||v==='true';else e.value=v}}
function share(f){const p=new URLSearchParams(new FormData(f));$$('input[type=checkbox]',f).forEach(b=>{if(b.checked)p.set(b.name,'on')});return`${location.origin}${location.pathname}?${p}`}
function csv(f){const text=$('[data-result]',f.closest('[data-tool-shell]')).textContent.replace(/\s+/g,' ').trim(),rows=[['field','value'],['tool',f.dataset.tool],['result',text],['boundary',BOUNDARY],...Object.entries(input(f)).map(([k,v])=>[k,String(v)])];const blob=new Blob([rows.map(r=>r.map(c=>`"${String(c).replaceAll('"','""')}"`).join(',')).join('\n')],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${f.dataset.tool}-result.csv`;a.click();URL.revokeObjectURL(a.href)}
$$('[data-tool-shell]').forEach(s=>{const f=$('form',s);hydrate(f);render(f);f.addEventListener('input',()=>render(f));f.addEventListener('submit',e=>{e.preventDefault();render(f)});$('[data-copy-result]',s).onclick=()=>navigator.clipboard.writeText($('[data-result]',s).textContent);$('[data-copy-assumptions]',s).onclick=()=>navigator.clipboard.writeText(BOUNDARY);$('[data-share]',s).onclick=()=>navigator.clipboard.writeText(share(f));$('[data-csv]',s).onclick=()=>csv(f);$('[data-print]',s).onclick=()=>print()});
