export const SOURCES=Object.freeze({doe:{name:'DOE Room Air Conditioners',url:'https://www.energy.gov/energysaver/room-air-conditioners',last_checked_at:'2026-05-22'},portable:{name:'DOE Portable Air Conditioners Test Procedure',url:'https://www.energy.gov/eere/buildings/articles/energy-conservation-program-test-procedure-portable-air-conditioners',last_checked_at:'2026-05-22'},energyStar:{name:'ENERGY STAR Certified Dehumidifiers',url:'https://www.energystar.gov/productfinder/product/certified-dehumidifiers/results',last_checked_at:'2026-05-22'},hvi:{name:'HVI Bathroom Ventilation',url:'https://www.hvi.org/resources/publications/bathroom-ventilation/',last_checked_at:'2026-05-22'},acca:{name:'ACCA Technical Manuals',url:'https://www.acca.org/standards/technical-manuals',last_checked_at:'2026-05-22'},epa:{name:'EPA Indoor Air and Mold Guidance',url:'https://www.epa.gov/mold',last_checked_at:'2026-05-22'}});
export const BOUNDARY='Educational preliminary estimate only. Not Manual J, Manual S, Manual D, code-compliant duct design, mold remediation, combustion safety, electrical sizing, medical advice, or final product selection.';
export const AC=Object.freeze({baseBtuPerSqft:20,shade:-.10,sun:.10,extraPersonBtu:600,kitchenExtraBtu:4000,baseHeightFt:8,rangeLow:.9,rangeHigh:1.1,common:[5000,6000,8000,10000,12000,14000,15000,18000,24000],source:SOURCES.doe});
export const VENT=Object.freeze({bathMinCfm:50,bathCfmPerSqft:1,fixture:{toilet:50,shower:50,tub:50,jettedTub:100},source:SOURCES.hvi});
export const DEHUM=Object.freeze({unit:'pints_per_day',source:SOURCES.energyStar});
export const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
export const round=(v,s=1)=>Math.round(v/s)*s;
export const up=(v,s=1)=>Math.ceil(v/s)*s;
export const fmt=(v,d=0)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:d}).format(n(v));
export function areaSqft({lengthFt=12,widthFt=10,areaSqft=0}={}){return n(areaSqft)>0?n(areaSqft):Math.max(0,n(lengthFt))*Math.max(0,n(widthFt))}
export function volumeCuft({lengthFt=12,widthFt=10,heightFt=8,ceilingHeightFt}={}){return areaSqft({lengthFt,widthFt})*Math.max(1,n(ceilingHeightFt??heightFt,8))}
export function btuToTons(btu){return n(btu)/12000} export function tonsToBtu(tons){return n(tons)*12000} export function btuToKw(btu){return n(btu)*0.000293071} export function kwToBtu(kw){return n(kw)/0.000293071} export function pintsToLiters(p){return n(p)*0.473176473} export function litersToPints(l){return n(l)/0.473176473} export function achToCfm(volume,ach){return n(volume)*n(ach)/60} export function cfmToAch(cfm,volume){return n(volume)>0?n(cfm)*60/n(volume):0}
export function acBtu(input={}){const area=areaSqft(input),height=Math.max(1,n(input.ceilingHeightFt??input.heightFt,8));let base=area*AC.baseBtuPerSqft,mid=base,adjustments=[];if(input.sunExposure==='shaded'){let d=mid*AC.shade;mid+=d;adjustments.push(['Heavy shade',d,'-10%'])} if(input.sunExposure==='sunny'){let d=mid*AC.sun;mid+=d;adjustments.push(['Very sunny room',d,'+10%'])} const occ=Math.max(0,Math.round(n(input.occupants,2))); if(occ>2){let d=(occ-2)*AC.extraPersonBtu;mid+=d;adjustments.push(['Additional occupants',d,'600 BTU/h each after two people'])} if(input.kitchen){mid+=AC.kitchenExtraBtu;adjustments.push(['Kitchen or heat source',AC.kitchenExtraBtu,'+4,000 BTU/h'])} if(height!==AC.baseHeightFt){let before=mid;mid*=height/AC.baseHeightFt;adjustments.push(['Ceiling height',mid-before,'advanced height factor'])} if(input.insulation==='poor'){let d=mid*.1;mid+=d;adjustments.push(['Poor insulation',d,'cautionary +10%'])} if(input.insulation==='good'){let d=mid*-.05;mid+=d;adjustments.push(['Good insulation',d,'cautionary -5%'])} const range={low:Math.max(0,round(mid*AC.rangeLow,500)),high:Math.max(0,round(mid*AC.rangeHigh,500))}; const common=AC.common.filter(x=>x>=range.low&&x<=range.high+1000);return{areaSqft:area,volumeCuft:area*height,baseBtu:base,adjustedBtu:mid,range,tonsLow:btuToTons(range.low),tonsHigh:btuToTons(range.high),commonSizes:common.length?common:[up(range.high,1000)],adjustments,warnings:[BOUNDARY,'Room AC estimates are not Manual J and must not be used for whole-home HVAC equipment selection.',...(input.sunExposure==='sunny'?['Direct sun and large west-facing windows can increase cooling load.']:[]),...(input.kitchen?['Kitchen and equipment heat can make comfort less predictable.']:[])]}}
export function dehumidifierBase(area,damp='damp'){const rows=[[500,{slightly:[20,30],damp:[25,35],very:[35,50],wet:[50,70]}],[1000,{slightly:[30,40],damp:[35,50],very:[50,70],wet:[70,90]}],[1500,{slightly:[40,50],damp:[50,70],very:[70,90],wet:[90,110]}],[99999,{slightly:[50,70],damp:[70,90],very:[90,120],wet:[120,150]}]];let key=damp==='slightly-damp'?'slightly':damp==='very-damp'?'very':damp;return Object.fromEntries(['low','high'].map((k,i)=>[k,rows.find(r=>area<=r[0])[1][key][i]]))}
export function dehumidifier(input={}){const area=Math.max(1,n(input.areaSqft,1000)),base=dehumidifierBase(area,input.dampness),adj=[];let low=base.low,high=base.high;if(input.basement){low+=5;high+=10;adj.push('Basement/below-grade adjustment')} if(n(input.temperatureF,70)<60)adj.push('Cool temperature can reduce removal rate; verify low-temperature operation.');let warnings=[BOUNDARY,'Dehumidifier sizing is not mold remediation or waterproofing.']; if(input.waterIntrusion)warnings.push('Water intrusion present: repair the water source before relying on a dehumidifier.'); if(!input.continuousDrain)warnings.push('A continuous drain or pump may be needed for unattended operation.');return{areaSqft:area,range:{low,high},productClass:high<=35?'compact':high<=55?'mid-size':high<=80?'large':'high-capacity',drainageRecommendation:input.continuousDrain?'Continuous drain selected. Verify hose/pump installation.':'Plan bucket emptying or choose a continuous drain model.',adjustments:adj,warnings}}
export function cfmByAch(input={}){const volume=volumeCuft(input),targetAch=Math.max(0,n(input.targetAch,6));return{volumeCuft:volume,targetAch,cfm:achToCfm(volume,targetAch),warnings:[BOUNDARY,'CFM/ACH math does not design ducts, prove indoor air quality, or establish code compliance.']}}
export function ach(input={}){const volume=volumeCuft(input),cfm=Math.max(0,n(input.cfm,100));return{volumeCuft:volume,cfm,ach:cfmToAch(cfm,volume),warnings:[BOUNDARY,'ACH is an airflow ratio, not a guarantee of health, source control, or code compliance.']}}
export function bathFan(input={}){const area=Math.max(1,n(input.areaSqft,80)),areaRule=Math.max(area*VENT.bathCfmPerSqft,VENT.bathMinCfm),fixture=Math.max(0,n(input.toilet,1))*50+Math.max(0,n(input.shower,1))*50+Math.max(0,n(input.tub,0))*50+Math.max(0,n(input.jettedTub,0))*100;let rec=up(Math.max(areaRule,fixture),10),warnings=[BOUNDARY,'Bathroom fan sizing must also consider duct length, elbows, fan curve, sone rating, installation manual, and local code.']; if(n(input.ductLengthFt,0)>25)warnings.push('Long duct runs and bends can reduce delivered airflow.');return{areaSqft:area,areaRuleCfm:areaRule,fixtureRuleCfm:fixture,recommendedCfm:rec,warnings}}
export function garageVent(input={}){const r=cfmByAch({...input,lengthFt:n(input.lengthFt,20),widthFt:n(input.widthFt,20),heightFt:n(input.heightFt,9)});return{...r,warnings:[BOUNDARY,'Garage estimate is educational only and must not be used for CO control, combustion appliances, commercial garages, or code compliance.','Use CO detectors and consult a qualified professional for vehicle exhaust or fuel-burning equipment.']}}
